### ISSUE TITLE
OperationalError in catalog.search()

### ISSUE THREAD

**Issue by pesekon2** [yannforget/pylandsat#2]
When I try to run the snippet from README, I always end up in an `OperationalError`. 

Using `pylandsat` version 0.1 from PyPI.

In:

```python
from datetime import datetime

from shapely.geometry import Point
from pylandsat import Catalog, Product

catalog = Catalog()

begin = datetime(2000, 1, 1)
end = datetime(2010, 1, 1)
geom = Point(4.34, 50.85)

# Results are returned as a list
scenes = catalog.search(
    begin=begin,
    end=end,
    geom=geom,
    sensors=['ETM', 'LC08']
)
```

Out:

```python
OperationalError                          Traceback (most recent call last)
<ipython-input-10-f10d92c633c0> in <module>
     11 
     12 # Results are returned as a list
---> 13 scenes = catalog.search(
     14     begin=begin,
     15     end=end,

~/workspace/qcmms/.direnv/python-3.8.5/lib/python3.8/site-packages/pylandsat/catalog.py in search(self, begin, end, path, row, geom, maxcloud, sensors, tiers, slc)
     95                 params=(path, row, begin, end, maxcloud, sensors, tiers))
     96         elif geom:
---> 97             scenes = self.db.query(
     98                 query=queries.CATALOG_SEARCH_GEOM,
     99                 params=(geom, begin, end, maxcloud, sensors, tiers, geom))

~/workspace/qcmms/.direnv/python-3.8.5/lib/python3.8/site-packages/pylandsat/database.py in query(self, query, params)
     70         if params:
     71             query, params = _format_placeholders(query, params)
---> 72             c.execute(query, params)
     73         else:
     74             c.execute(query)

OperationalError: no such table: catalog
```

**Comment by psychemedia** [comment]
Did you created the initial database and synchronise the catolog index first?

For example:

```python
from pylandsat.database import sync_catalog

sync_catalog()
```

**Comment by pesekon2** [comment]
Well, not at the beginning. I have scrips that are working fine with `pylandsat` so that was not a problem for me; the issue was meant more to note that maybe the catalogue synchronization should be mentioned in the code snippet in README. I know that the sync is mentioned above [here](https://github.com/yannforget/pylandsat#search-for-scenes), but when someone installs the package and wants to try a quick snippet to test it, the user tries the first Python code in README.

**Comment by psychemedia** [comment]
I just tried from the README too and even after the above catalog synch, there's a missing `wrs` table error - and it seems the download URL for that data now 404s.

**Comment by yannforget** [comment]
Thanks for the bug reports,

Yes the package is due for an update that I will try to push ASAP. Some URLs changed. The WRS error is due to #5 

Sorry for the inconvenience!

Yann

**Comment by yannforget** [comment]
> 
> 
> Thanks for the bug reports,
> 
> Yes the package is due for an update that I will try to push ASAP. Some URLs changed. The WRS error is due to #5
> 
> Sorry for the inconvenience!
> 
> Yann

I pushed an update today (v0.5). This issue should be fixed

**Comment by pesekon2** [comment]
Thanks for the update. The [Python snippet](https://github.com/yannforget/pylandsat#search-the-catalog) from the README could still fail if the catalog is not synced. Maybe it would be helpful to put there something like the following? (having a function to check if the catalog is synced would allow to put this into an `if` clause, but that is more an enhancement proposal and not actually part of this issue)

```python
# in the case the catalog has not been synced manually, run the following
catalog.sync()
```

However, even if syncing the catalog, I still run into the issue with the `wrs` table. However, I have seen some issues during my GDAL compilation, so it is possible that it is not connected to the `pylandsat` code. Feel free to close the issue if no one else notices the same issue (probably @psychemedia to check it?):

```python
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-4-c376aacb7c9c> in <module>
      1 # Results are returned as a list
----> 2 scenes = catalog.search(
      3     begin=begin,
      4     end=end,
      5     geom=geom,

/tmp/.direnv/python-3.9.1+/lib/python3.9/site-packages/pylandsat/catalog.py in search(self, begin, end, path, row, geom, maxcloud, sensors, tiers, slc)
     95                 params=(path, row, begin, end, maxcloud, sensors, tiers))
     96         elif geom:
---> 97             scenes = self.db.query(
     98                 query=queries.CATALOG_SEARCH_GEOM,
     99                 params=(geom, begin, end, maxcloud, sensors, tiers, geom))

/tmp/.direnv/python-3.9.1+/lib/python3.9/site-packages/pylandsat/database.py in query(self, query, params)
     70         if params:
     71             query, params = _format_placeholders(query, params)
---> 72             c.execute(query, params)
     73         else:
     74             c.execute(query)

OperationalError: no such table: wrs
```

**Comment by yannforget** [comment]
Thanks for the follow-up.

> Thanks for the update. The [Python snippet](https://github.com/yannforget/pylandsat#search-the-catalog) from the README could still fail if the catalog is not synced. Maybe it would be helpful to put there something like the following? (having a function to check if the catalog is synced would allow to put this into an `if` clause, but that is more an enhancement proposal and not actually part of this issue)
> 
> ```python
> # in the case the catalog has not been synced manually, run the following
> catalog.sync()
> ```

I agree it should be added. I'm gonna add a separate issue and look into adding it to the future release

> However, even if syncing the catalog, I still run into the issue with the `wrs` table. However, I have seen some issues during my GDAL compilation, so it is possible that it is not connected to the `pylandsat` code. Feel free to close the issue if no one else notices the same issue (probably @psychemedia to check it?):
> 


Even with:

``` python
from pylandsat import database

database.sync_wrs()
```

or

``` sh
pylandsat sync-database -f
```

? The database exists but has been created with the previous version when the URL to the WRS shapefiles were outdated.

Please note that if you sync the database using the Python API instead of with the CLI, you need to call two functions:

``` python
from pylandsat.database import sync_catalog, sync_wrs

sync_catalog()
sync_wrs()
```

**Comment by pesekon2** [comment]
> Thanks for the follow-up.

Well, if we want the open source world to show its advantages, we should also use them, right? Thank you for keeping code like this alive.

> I agree it should be added. I'm gonna add a separate issue and look into adding it to the future release

Great! Thanks.

> > However, even if syncing the catalog, I still run into the issue with the `wrs` table. However, I have seen some issues during my GDAL compilation, so it is possible that it is not connected to the `pylandsat` code. Feel free to close the issue if no one else notices the same issue (probably @psychemedia to check it?):
> 
> Even with:
> 
> ```python
> from pylandsat import database
> 
> database.sync_wrs()
> ```

Okay, my fault. With `sync_wrs()`, the catalog search works. Closing this issue then (the main topic of this issue solved with version 0.5). Thanks. 

(found another issue that affects the README snippet, but going to open a new issue for that one)

**Comment by bholtdwyer** [comment]
Hi! I've been trying to run the code snippet in the "Python API" section of the readme. First I was getting sqlite3 errors, which I solved by following the instructions [here](https://stackoverflow.com/questions/8590599/sqlite-load-extension-fail-for-spatialite-in-python) (might be worth noting that Windows installs seem to require manual patching of some dlls and paths). However, even after fixing that problem, when I try to run the "search catalog" snippet, I get the following error on the "scenes = catalog.search(..." line:

```
Traceback (most recent call last):

  File "C:\Users\holtd\.spyder-py3\temp.py", line 123, in <module>
    scenes = catalog.search(

  File "C:\Users\holtd\anaconda3\lib\site-packages\pylandsat\catalog.py", line 97, in search
    scenes = self.db.query(

  File "C:\Users\holtd\anaconda3\lib\site-packages\pylandsat\database.py", line 72, in query
    c.execute(query, params)

OperationalError: no such table: wrs
```

Finding this issue page, I tried running the following lines to set up the wrs table, but I get a HTTP 301 error, as shown below.

```
from pylandsat.database import sync_catalog, sync_wrs

sync_catalog()
sync_wrs()
index.csv.gz: : 768MB [01:10, 10.9MB/s]                          
100%|█████████▉| 9608135/9608136 [03:48<00:00, 42124.13 rows/s]
Traceback (most recent call last):


  File "C:\Users\holtd\.spyder-py3\temp.py", line 94, in <module>
    sync_wrs()

  File "C:\Users\holtd\anaconda3\lib\site-packages\pylandsat\database.py", line 134, in sync_wrs
    fpath = utils.download_file(WRS_URL, tmpdir, progressbar=True)

  File "C:\Users\holtd\anaconda3\lib\site-packages\pylandsat\utils.py", line 79, in download_file
    raise requests.exceptions.HTTPError(str(r.status_code))

HTTPError: 301
```

Any idea what I can do to fix this?
